### ISSUE TITLE
release on github?

### ISSUE THREAD

**Issue by ignatenkobrain** [dgerber/rfc3987#10]

**Comment by ignatenkobrain** [comment]
please push all releases on github.

**Comment by dgerber** [comment]
Please see PyPI for packaged distributions. I do not see any reason to duplicate it on github -- and also no simple way to make it automatic.

**Comment by ignatenkobrain** [comment]
@dgerber `git tag X.Y && git push origin X.Y` is not enough?

**Comment by dgerber** [comment]
That is what I have done so far: each release has a tag, pushed to github. The "built" wheels and sdist are only on PyPI.

**Comment by ignatenkobrain** [comment]
@dgerber that's what I was asking for (because not all tags were pushed).
