### ISSUE TITLE
Square brackets are parsed incorrectly

### ISSUE THREAD

**Issue by festinuz** [dgerber/rfc3987#13]
example
```python
>>> uri = "http://www.boolean.ru/index.php/ru/component/myextensions/?cid[0]=89&view=customerdetails"
>>> rfc3987.parse(uri)
```

expected result:
```python

>>> {'scheme': 'http', 'fragment': None, 'authority': 'www.boolean.ru', 'query': 'cid[0]=89&view=customerdetails', 'path': '/index.php/ru/component/myextensions/'}
```

actual result:
```python

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mortphine/.virtualenvs/search_crawler/lib/python3.5/site-packages/rfc3987.py", line 461, in parse
    raise ValueError('%r is not a valid %r.' % (string, rule))
ValueError: 'http://www.boolean.ru/index.php/ru/component/myextensions/?cid[0]=89&view=customerdetails' is not a valid 'IRI_reference'.

```

**Comment by dgerber** [comment]
It seems correct: the query part can include sub-delims but not (all) gen-delims (see https://tools.ietf.org/html/rfc3986#appendix-A).

**Comment by festinuz** [comment]
I'm sorry, but i dont get it yet.
The uri is valid, and is not auto-escaped by browsers. It is actually parsed well by online services such as [this one](https://www.freeformatter.com/url-parser-query-string-splitter.html) ([screenshot](https://i.imgur.com/8RCm4RF.png)).

Also in [RFC 3987](https://www.ietf.org/rfc/rfc3987.txt) on **page 12** it says:

> Systems accepting IRIs MAY also deal with the printable characters in
>    US-ASCII that are not allowed in URIs, namely "<", ">", '"', space,
>    "{", "}", "|", "\", "^", and "`", in step 2 above.  If these
>    characters are found but are not converted, then the conversion
>    SHOULD fail.  Please note that the number sign ("#"), the percent
>    sign ("%"), and the square **bracket characters** ("[", "]") are not part
>    of the above list and **MUST NOT be converted**. 


I mean it seems to me that this is not a valid **URI**, but a valid **IRI**.

Can you please explain what im getting wrong here?

**Comment by dgerber** [comment]
Right, browsers try to be friendly to users and do some conversions between what is input or displayed and valid URIs... This library implements the specification more strictly.

Square brackets are for IP literals. As you quoted they explicitly "MUST NOT be converted" even in the query string, where it might be in practice harmless -- therefore (or by mistake) some user-facing applications ignore the spec and accept those as input.

**Comment by festinuz** [comment]
Yup, i get it now. Thank you!
