### ISSUE TITLE
Support for RFC 6874?

### ISSUE THREAD

**Issue by handrews** [dgerber/rfc3987#18]
[RFC 6874](https://datatracker.ietf.org/doc/html/rfc6874) updates RFC 3986 (and therefore 3987) with additional syntax for IPv6 Zone Identifiers.  For example, `"http://[fe80::221:b7ff:fe8a:57d5%25en4]/"` is valid according to RFC6874, but the `%25en4` part (an encoded `%` followed by the zone identifier `en4`) is deemed invalid by the `rfc3987` package.

PS: thank you for providing what is, AFAICT, the only Python library that correctly and efficiently implements RFC 3986 and 3987!  I've yet to find a case that breaks it (I'm not counting this issue, as it's a revision in an RFC published a little after you started this project based on the commit log)

**Comment by dgerber** [comment]
I suppose this might be in-scope for this package, yes.

The simplest change would be to just relax the regexp for IPLiteral accordingly.

**Comment by handrews** [comment]
Sounds about right.  Are you planning to do this or would you like a PR?  (it might be a couple weeks before I get to it).

**Comment by dgerber** [comment]
Sorry for the hiatus... I could do it myself some day, but if you want to speed things up, please go ahead.

Note however: the project is moving to https://codeberg.org/atufi/rfc3987/ .

**Comment by dgerber** [comment]
https://codeberg.org/atufi/rfc3987/issues/17
