### ISSUE TITLE
Unexpected invalid uri reported by parse

### ISSUE THREAD

**Issue by danielnelson** [dgerber/rfc3987#6]
The parse is reporting this uri as invalid but I think it is valid, it has an accented e (c3 a9 in utf-8). I have tried with re and regex:

	$ cat test.py
	import rfc3987
	u = 'https://twitter.com/search?q=%23Démission&src=hash'
	rfc3987.parse(u, 'URI')

	$ python3.4 test.py
	Traceback (most recent call last):
	  File "test.py", line 4, in <module>
		rfc3987.parse(u, 'URI')
	  File "/home/dbn/usr/venv/lib/python3.4/site-packages/rfc3987.py", line 442, in parse
		raise ValueError('%r is not a valid %r.' % (string, rule))
	ValueError: 'https://twitter.com/search?q=%23Démission&src=hash' is not a valid 'URI'

**Comment by dgerber** [comment]
It's not valid as URI, but as IRI (those with non-ASCII characters): `rfc3987.parse(u, 'IRI')`.
