### ISSUE TITLE
License question: different license possible for use as library?

### ISSUE THREAD

**Issue by ViktorAtD2L** [dgerber/rfc3987#7]
Hi,

I'm interested in using rfc3987 purely as a library but have restrictions on the licenses I may use under some situations -- are you willing to permit such use under a license other than GPLv3? For example, would you permit such use under LGPLv3 within the confines of another project that is also LGPLed? Thanks.

**Comment by dgerber** [comment]
Sorry, while not entirely closed to economic incentives to switch to LGPL, I have a preference for GPL. If it is that important and you have resources for your project, please let me know by email.

By the way, as you are not the first to ask: someone make a package named rfc3986. Maybe that suits your needs.

**Comment by ViktorAtD2L** [comment]
Thank you for your response.

**Comment by tony** [comment]
Most people can't use this package due to the license.

**Comment by jpmckinney** [comment]
This can be used instead in most cases (MIT license): https://pypi.org/project/rfc3986-validator/

**Comment by tony** [comment]
@jpmckinney thank you, https://github.com/naimetti/rfc3986-validator looks nice
